define(function(){
return "<div class='option'>" //<!-- //行情图 -->
	+"<section class='stock-data'>"
		+"<ul>"
			+"<li><h3></h3><p></p></li>"
			+"<li></li>"
			+"<li></li>"
		+"</ul>"
	+"</section>"
	+"<div class='stock-menu'>"
		+"<div class='currentLine'></div>"
		+"<li class='current'>分时</li>"
		+"<li>日K</li>"
		+"<li>周K</li>"
		+"<li>月K</li>"
	+"</div>"
	+"<section class='kline'>"
		+"<div class='stock-ma'><li></li><li></li><li></li></div>"
		+"<article class='stock-pic'>" //<!-- //分时 K线 等图 -->
				+"<div class='canvassize'>"
					+"<div class='canvasbox'>"
						+"<div class='minute-canvas'>"
							+"<div class='top-pic'>"
								+"<canvas class='draw'></canvas>"
								+"<canvas class='av ps'></canvas>"
								+"<canvas class='bg ps'></canvas>"
							+"</div>"
							+"<div class='bottom-pic'>"
								+"<canvas class='draw'></canvas>"
								+"<canvas class='bg ps'></canvas>"
							+"</div>"
						+"</div>"
						+"<div class='day-canvas'>"
							+"<div class='top-pic'>"
								+"<canvas class='draw'></canvas>"
								+"<canvas class='ma5 ps'></canvas>"
								+"<canvas class='ma10 ps'></canvas>"
								+"<canvas class='ma20 ps'></canvas>"
								+"<canvas class='bg ps'></canvas>"
								/** +"<div class='stock-zoom'>"
									+"<div class='s-b'>"
										+"<div class='v-line'></div>"
										+"<div class='h-line'></div>"
									+"</div>"
									+"<div class='c-b '>"
										+"<div class='v-line'></div>
									+"</div>"
								+"</div>" **/
							+"</div>"
							+"<div class='bottom-pic'>"
								+"<canvas class='draw'></canvas>"
								+"<canvas class='bg ps'></canvas>"
							+"</div>"
						+"</div>"
						+"<div class='week-canvas'>"
							+"<div class='top-pic'>"
								+"<canvas class='draw'></canvas>"
								+"<canvas class='ma5 ps'></canvas>"
								+"<canvas class='ma10 ps'></canvas>"
								+"<canvas class='ma20 ps'></canvas>"
								+"<canvas class='bg ps'></canvas>"
							+"</div>"
							+"<div class='bottom-pic'>"
								+"<canvas class='draw'></canvas>"
								+"<canvas class='bg ps'></canvas>"
							+"</div>"
						+"</div>"
						+"<div class='month-canvas'>"
							+"<div class='top-pic'>"
								+"<canvas class='draw'></canvas>"
								+"<canvas class='ma5 ps'></canvas>"
								+"<canvas class='ma10 ps'></canvas>"
								+"<canvas class='ma20 ps'></canvas>"
								+"<canvas class='bg ps'></canvas>"
							+"</div>"
							+"<div class='bottom-pic'>"
								+"<canvas class='draw'></canvas>"
								+"<canvas class='bg ps'></canvas>"
							+"</div>"
						+"</div>"
					+"</div>"
				+"</div>"
				+"<div class='stock-line'>"
					+"<div class='hline' style='display:none'>"
						+"<div class='line'></div>"
						+"<div class='l_num'>0.00</div>"
						+"<div class='r_num'>0.00%</div>"
					+"</div>"
					+"<div class='vline' style='display:none'>"
						+"<div class='line'></div>"
						+"<div class='num'>09:30</div>"
					+"</div>"
					+"<ul class='left'>"
						+"<li class='red'></li>"
						+"<li class='red'></li>"
						+"<li></li>"
						+"<li class='green'></li>"
						+"<li class='green'></li>"
					+"</ul>"
					+"<ul class='right'>"
						+"<li class='red'></li>"
						+"<li class='red'></li>"
						+"<li></li>"
						+"<li class='green'></li>"
						+"<li class='green'></li>"
					+"</ul>"
				+"</div>"
			+"</article>"
			+"<time class='stock-time'>"
				+"<ul>"
					+"<li>09:30</li>"
					+"<li>11:30/13:00</li>"
					+"<li>15:00</li>"
				+"</ul>"
			+"</time>"
	+"</section>"
+"</div>"
});